update latest probate common version
hmcts/probate-business-service pull request #632
Opened 2022-03-17 11:33 UTC by srochani

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-03-17 11:35 UTC, isha2040 approved these changes

2022-03-18 12:24 UTC, nigeldunne approved these changes

2022-03-22 09:44 UTC, nigeldunne requested changes
We're going to close this PR and revert the changes from probate-commons

2022-04-08 15:56 UTC, srochani commented
Closed as its not require

2022-04-08 15:56 UTC, closed without merging